### ISSUE TITLE
can't get configured on Synology NAS

### ISSUE THREAD

**Issue by mbierman** [Schlabbi/docker-notify#4]
Hi, I am trying to run docker-notify on my synology NAS. My config.json looks like the file below but the container keeps restarting. Presumably I haven't configured something correctly.

```
{
    "notifyServices": [
        {
            "image": "oznu/homebridge:latest",
            "actions": [
                {
                    "type": "webHook",
                    "instance": "homebridgeHook"
                }
            ]
        },
        {
            "image": "jacobalberty/unifi:latest",
            "actions": [
                {
                    "type": "webHook",
                    "instance": "unifiHook"
                }
            ]
        }
    ],
    "webHooks": {
        "homebridgeHook": {
            "reqUrl": "https://maker.ifttt.com/...",
            "httpMethod": "GET"
        },
        "unifiHook": {
            "reqUrl": "https://maker.ifttt.com/t...",
            "httpMethod": "GET"
        }
    }
}
```

**Comment by mbierman** [comment]
So I _think_ I am running the container successfully now. all the logs show is
```
$ sudo docker logs d94376f7fc27
Checking for updated repositories

```

is that a sign of success?

**Comment by Schlabbi** [comment]
Looks good, maybe the log output there could be better. But as long as you don't see any errors in the logs everything should be fine.

**Comment by mbierman** [comment]
Great, thank you. Three questions: 

1. Would you consider adding date stamps to the log file when a check is made?

1. Would you consider adding a configuration for how often to check for updates? 

1. If I wrote up instructions for using this container on a Synology would you consider adding it to your wiki so others would find it?

**Comment by Schlabbi** [comment]
1. Yeah, that makes sense. Will do that.

2. You can already do that (it's missing in the Readme, my bad). Just set the environment variable `checkInterval` to the time interval (in hours) that you want. You should be able to pass in values like `0.5` but I have to admit I cannot remember if I have tested this case.

3. Sure thing, just open an issue or a PR directly.

I'll open issues for 1 and 2 real quick so I have it documented and don't forget about it. Thanks for your input.

**Comment by Schlabbi** [comment]
Update for 2.:

I looked into it real quick and the JS script reads the variable from the environment. However, there is a `checkInterval` field in the config example. I'll look into this one closer as this should definitely be read from the config file instead of environment.

**Comment by mbierman** [comment]
Are you sure the `checkInterval` is in hour units? I tried adding it as an ENV variable with a value of 12 and it is not happening 1/12 hours. I also tried adding it to the `config.json` and I think that caused a configuration problem so I removed it.

**Comment by Schlabbi** [comment]
No, I was wrong. The variable is actually in minutes and it was not correctly read from the config file.

I fixed this one.

Also: Dates are now printed in every log statement. Will look at your PR soon.

**Comment by mbierman** [comment]
Fantastic! Thank you so much. FYI I added the `TZ` variable to the environment which nicely set the timestamp to my local time. Might be a nice suggestion to add to the documents as well. 

I really appreciate your help. 

Also, I hope the PR is o.k. The links to the graphics might be wrong because I was having trouble testing. If you want to open the wiki I could test it there and make sure it is all good so you don't have to mess with it. Whatever is easier for you. 

Many thanks again.

**Comment by Schlabbi** [comment]
Thanks for the PR, is there anything else to this issue or can we close this?

**Comment by mbierman** [comment]
Nothing else, Closing.
