### ISSUE TITLE
testing email addresses

### ISSUE THREAD

**Issue by mbierman** [Schlabbi/docker-notify#8]
I tried to configure  a mailhook and apparently I didn't do something right. The problem is the docker containers I track don't change often so making a change I may have to wait quite a while before I can "test". Is there a way to make a trigger for the mail event on demand? 

![image](https://user-images.githubusercontent.com/1205471/98186268-3b765980-1ec3-11eb-8300-81d86406dfd0.png)

**Enhancement request**
jwhat if when the docker-notify container starts it sends an email and webhook notification indicating the container started successfully for any that are configured?

**Update**
I might have found my problem but the enhancement request would really help so I can test to see if I fixed the issue! 

Also, does anything about this config jump out as wrong? 

```
{
	"checkInterval": 1440,
    "notifyServices": [
        {
            "image": "oznu/homebridge:latest",
            "actions": [
				{
	               "type": "mailHook",
	               "instance": "generalMail",
	               "recipient": "***"
	            },
                {
                    "type": "webHook",
                    "instance": "homebridgeHook"
                }
            ]
        },
        {
            "image": "jacobalberty/unifi:latest",
            "actions": [
				{
	               "type": "mailHook",
	               "instance": "generalMail",
	               "recipient": "***"
	            },
                {
                    "type": "webHook",
                    "instance": "unifiHook"
                }
            ]
        },
                {
            "image": "Schlabbi/docker-notify:latest",
            "actions": [
				{
	               "type": "mailHook",
	               "instance": "generalMail",
	               "recipient": "***"
	            },
                {
                    "type": "webHook",
                    "instance": "dockernotifyHook"
                }
            ]
        }
    ],
	"smtpServer": {
		"generalMail": {
			"host": "smtp.google.com",
			"port": 587,
			"username": "a@b.com",
			"password": "***",
			"sendername": "Docker-Notify",
			"senderadress": "b@b.com"
		}
	},
    "webHooks": {
        "homebridgeHook": {
            "reqUrl": "https://maker.ifttt.com/tr...",
            "httpMethod": "GET"
        },
        "unifiHook": {
            "reqUrl": "https://maker.ifttt.com/...",
            "httpMethod": "GET"
        },
        "dockernotifyHook": {
            "reqUrl": "https://maker.ifttt.com/...",
            "httpMethod": "GET"
        }
    }
}
```

**Comment by Schlabbi** [comment]
That enhancement is a good idea. Maybe we should add a flag for testing. If this flag is set, it will send a test mail and hit all webhooks on startup. This way you can verify your setup and then just disable the flag so you don't get a mail or webhook call every time the container restarts.

Also I think the mail server connection should be verified on each container start and immediately log an error if there is a misconfiguration. At least for mail this should suffice, but this is not the case right now. However, this would not help in detecting configuration errors in the webhooks.

**Comment by mbierman** [comment]
I like your idea. That sounds perfect. Would the flag be an environment variable or something in config.json? 

I tried what you said but maybe I did something wrong. Do you support SSL or TLS for the email? I am not seeing any email or anything in the log but I am seeing the webhook fire.

**Comment by Schlabbi** [comment]
It should have worked, at least the container tried to send a mail. That currently only happens when there is a new update (even if it was a fake one in this case).

In general I do support SSL/TLS. To send mails I just use [this package](https://www.npmjs.com/package/nodemailer) and I give your configuration directly to the package.

Can you try to set `secure: false` just to test the connection? Or use another port?

**Comment by mbierman** [comment]
I am using gmail. The package you point to says that is challenging. I'll play around with it. I don't see any reason to keep this open though. Thank you.
